apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: backend-green
  labels:
    app: backend
    kube-monkey/enabled: "enabled"
    kube-monkey/identifier: "backend"
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: backend
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "backend"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
        color: green

    spec:
      containers:
      - name: backend
        image: johnlive/backend_server_green:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3001
