apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: frontend-blue
  labels:
    app: frontend
    kube-monkey/enabled: "enabled"
    kube-monkey/identifier: "frontend"
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: "1"
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: frontend
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "frontend"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: "1"
        color: blue
    spec:
      containers:
      - name: frontend
        image: johnlive/frontend-blue
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
