kubectl apply -f deployBackendDataMSBlue.yaml
kubectl apply -f deployBackendDataMSGreen.yaml
kubectl apply -f deployBackendDropboxBlue.yaml
kubectl apply -f deployBackendDropboxGreen.yaml
kubectl apply -f deployBackendServerBlue.yaml
kubectl apply -f deployBackendServerGreen.yaml
kubectl apply -f deployDietBlue.yaml
kubectl apply -f deployDietGreen.yaml
kubectl apply -f deployFitbitBlue.yaml
kubectl apply -f deployFitbitGreen.yaml
kubectl apply -f deployFitnessBlue.yaml
kubectl apply -f deployFitnessGreen.yaml
kubectl apply -f deployFrontendBlue.yaml
kubectl apply -f deployFrontendGreen.yaml
kubectl apply -f serviceBackendDataMSBlue.yaml
kubectl apply -f serviceBackendDataMSGreen.yaml
kubectl apply -f serviceBackendDropboxBlue.yaml
kubectl apply -f serviceBackendDropboxGreen.yaml
kubectl apply -f serviceBackendServerBlue.yaml
kubectl apply -f serviceBackendServerGreen.yaml
kubectl apply -f serviceDietBlue.yaml
kubectl apply -f serviceDietGreen.yaml
kubectl apply -f serviceFitbitBlue.yaml
kubectl apply -f serviceFitbitGreen.yaml
kubectl apply -f serviceFitnessBlue.yaml
kubectl apply -f serviceFitnessGreen.yaml
kubectl apply -f serviceFrontendBlue.yaml
kubectl apply -f serviceFrontendGreen.yaml