apiVersion: v1
kind: Service
metadata:
  name: fitbit
  annotations:
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
  labels:
    app: fitbit
spec:
  type: LoadBalancer
  # loadBalancerIP: 10.10.10.10
  ports:
  - port: 5004
    targetPort: 5004
    name: http
    protocol: TCP
    nodePort: 30052
  selector:
    app: fitbit
    color: blue
  externalIPs:
  - 149.165.170.134

